---
- name: Setup Dynamic PHP Portfolio
  hosts: localhost
  become: true

  vars_files:
    - ansible-vault/secrets.yml

  tasks:

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apache2
          - php
          - libapache2-mod-php
          - php-pgsql
          - postgresql
          - postgresql-contrib
          - python3-psycopg2
          - acl
        state: present

    - name: start and enable apache2 service
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
    
    - name: start and enable postgresql service
      ansible.builtin.service: 
        name: postgresql
        state: started
        enabled: true

    - name: create postgres database
      become_user: postgres

      community.postgresql.postgresql_db:
        name: portfolio
        state: present
      

    
    - name: create postgres user
      become_user: postgres
      become: true

      community.postgresql.postgresql_user:
        name: portfolio_user
        password: "{{ postgres_password }}"
        priv: "portfolio:ALL"
        state: present
        
       

    - name: grant privileges to user on database
      community.postgresql.postgresql_privs:
        db: portfolio
        role: portfolio_user
        type: database
        privs: ALL
        state: present


    - name: copy PHP configuration file
      ansible.builtin.copy:
        src: files/index.php
        dest: /var/www/html/index.php
        owner: www-data
        group: www-data
        mode: '0644'
  

    - name: copy database configuration file
      ansible.builtin.copy:
        src: files/init.sql
        dest: /temp/init.sql
        owner: www-data 
        group: www-data
        mode: '0644'

    - name: run the SQL script to create the database and table
      become: true
      become_user: postgres
      
      ansible.builtin.command:
        cmd: psql -d portfolio -f /temp/init.sql
       

    - name: restart apache2 service
      ansible.builtin.service:
        name: apache2
        state: restarted
      
    

    # - name: Install Ansible
    #   pip:
    #     name: ansible
    #     state: present

   # - name: Clone the dynamic portfolio repository
    #   git:
    #     repo: '